.TH "Attach" 3 "Wed Aug 16 2017" "Drone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Attach
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBRudder\fP, \fBSensor< T >\fP, \fBSensor< double >\fP, and \fBThrust\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAttach\fP (double mass, double min, double max, double initial)"
.br
.ti -1c
.RI "const double \fBget_mass\fP ()"
.br
.ti -1c
.RI "const double \fBget_min\fP ()"
.br
.ti -1c
.RI "const double \fBget_max\fP ()"
.br
.ti -1c
.RI "double \fBget_current\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Attach::Attach (double mass, double min, double max, double initial)"
constructor of attach modules
.PP
\fBParameters:\fP
.RS 4
\fImass\fP the mass of the module 
.br
\fImin\fP the minimum of the range 
.br
\fImax\fP the maximum of the range 
.br
\fIinitial\fP the neutral value of the range 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double Attach::get_current ()"
get the current value
.PP
\fBReturns:\fP
.RS 4
current value 
.RE
.PP

.SS "const double Attach::get_mass ()"
get the mass of the module
.PP
\fBReturns:\fP
.RS 4
mass of the module 
.RE
.PP

.SS "const double Attach::get_max ()"
get the maximum of the range
.PP
\fBReturns:\fP
.RS 4
maximum of the range 
.RE
.PP

.SS "const double Attach::get_min ()"
get the minimum of the range
.PP
\fBReturns:\fP
.RS 4
minimum of the range 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Drone from the source code\&.
