.TH "md__r_e_a_d_m_e" 3 "Sat Aug 19 2017" "Drone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_edrone playground 
 \- this is a cpp learning project\&. It's a virtual drone inside a environment\&.
.PP
It lacks some kind of graphical visualization\&. It's just data\&.
.PP
.SS "License "
.PP
Do with it what you want\&. 
