.TH "Rudder" 3 "Sat Aug 19 2017" "Drone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rudder
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rudder\&.h>\fP
.PP
Inherits \fBAttach\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRudder\fP (double min_pos, double max_pos)"
.br
.in -1c
.SH "Detailed Description"
.PP 
general rudder 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Rudder::Rudder (double min_pos, double max_pos)"
rudder constructor
.PP
\fBParameters:\fP
.RS 4
\fImin_pos\fP minimum position of the rudder 
.br
\fImax_pos\fP maximum position of the rudder 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Drone from the source code\&.
