.TH "Thrust" 3 "Thu Aug 17 2017" "Drone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Thrust
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <thrust\&.h>\fP
.PP
Inherits \fBAttach\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThrust\fP (double min, double max)"
.br
.in -1c
.SH "Detailed Description"
.PP 
general thrust (or engine)\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Thrust::Thrust (double min, double max)"
basic constructor
.PP
\fBParameters:\fP
.RS 4
\fImin\fP minimum value (mostly 0) 
.br
\fImax\fP maximum value (the higher the more power) 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Drone from the source code\&.
