.TH "vect3d" 3 "Thu Aug 17 2017" "Drone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vect3d
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vect3d\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvect3d\fP (double x_val, double y_val, double z_val)"
.br
.ti -1c
.RI "\fBvect3d\fP ()"
.br
.ti -1c
.RI "\fBvect3d\fP \fBoperator+=\fP (const \fBvect3d\fP &a)"
.br
.ti -1c
.RI "\fBvect3d\fP \fBoperator*\fP (const double &a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
my vector struct 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "vect3d::vect3d (double x_val, double y_val, double z_val)\fC [inline]\fP"
create a vector with values
.PP
\fBParameters:\fP
.RS 4
\fIx_val\fP x value 
.br
\fIy_val\fP y value 
.br
\fIz_val\fP z value 
.RE
.PP

.SS "vect3d::vect3d ()\fC [inline]\fP"
create an empty vector with 0 0 0 
.SH "Member Function Documentation"
.PP 
.SS "\fBvect3d\fP vect3d::operator* (const double & a)\fC [inline]\fP"
multiplies vector with a double value 
.SS "\fBvect3d\fP vect3d::operator+= (const \fBvect3d\fP & a)\fC [inline]\fP"
adds vectors together 

.SH "Author"
.PP 
Generated automatically by Doxygen for Drone from the source code\&.
